# Modern docker-compose format - no version needed

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - redis_data:/data
    networks:
      - streamll_test

volumes:
  redis_data:
    driver: local

networks:
  streamll_test:
    driver: bridge