name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.13"]  # Min and max supported versions
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          uv sync --all-extras --dev
          uv pip install -e .

      - name: Run linting
        run: uv run ruff check . --ignore=T201,SIM117

      - name: Run unit tests
        run: |
          uv run pytest tests/unit -xvs --cov=src/streamll --cov-fail-under=70
        env:
          PYTHONPATH: .

      - name: Start test infrastructure
        run: |
          docker compose -f .github/docker-compose.test.yml up -d redis rabbitmq
          # Wait for services to be ready
          timeout 30 bash -c 'until docker exec $(docker ps -qf "name=redis") redis-cli ping 2>/dev/null; do sleep 1; done'
          echo "Redis is ready"

      - name: Run integration tests
        run: |
          export REDIS_URL="redis://localhost:6379"
          export RABBITMQ_URL="amqp://streamll_test:streamll_test@localhost:5672/streamll"
          uv run pytest tests/integration -v --tb=short || true
        continue-on-error: true  # Don't fail build if integration tests fail

      - name: Stop test infrastructure
        if: always()
        run: docker compose -f .github/docker-compose.test.yml down -v

  examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.11"

      - name: Install package
        run: |
          uv sync --all-extras
          uv pip install -e .

      - name: Test basic example imports
        run: |
          # Just ensure examples don't have syntax errors
          for example in examples/*.py; do
            echo "Checking $example"
            uv run python -m py_compile "$example"
          done
